name: Get & Cache dependencies
description: "Get the dependencies (via npm) and cache them"
runs:
  using: 'composite'
  inputs:
    caching:
      description: "Choose to run the caching or not"
      required: false
      default: 'true'
  steps:
    - name: Cache dependencies
      id: cache
      if: inputs.caching == 'true'
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
